"""
Synthetic test case runner.

Loads data/test_cases/synthetic_cases.json (generated by the LLM pipeline
when ANTHROPIC_API_KEY is available) and runs each case through the engine.

If the file does not exist, all tests are skipped gracefully.

The 20 cases are generated by `python -m cli run-pipeline` after an API key
is configured. Expected case categories:
  - 5 clearly eligible
  - 5 clearly ineligible (varying failing condition)
  - 5 edge cases (borderline, ambiguous)
  - 5 incomplete (missing key facts, tests partial resolution)
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from fact_graph.engine import FactGraphEngine
from fact_graph.schema import FactStatus, TestCase
from tests.fixtures.fema_ia_graph import build_fema_ia_graph

_CASES_PATH = Path(__file__).parent.parent / "data" / "test_cases" / "synthetic_cases.json"


def _load_cases() -> list[TestCase]:
    if not _CASES_PATH.exists():
        return []
    raw: list[dict] = json.loads(_CASES_PATH.read_text())  # type: ignore[type-arg]
    return [TestCase.model_validate(c) for c in raw]


_CASES = _load_cases()
_SKIP_MSG = (
    "Synthetic cases not found. Run `fact-graph run-pipeline` to generate them "
    "(requires ANTHROPIC_API_KEY)."
)


def _actual_determination(engine: FactGraphEngine) -> str:
    det = engine.get_determination()
    eligible_trace = det.terminal_facts.get("applicant_eligible_for_rental_assistance")
    if eligible_trace and eligible_trace.status == FactStatus.RESOLVED:
        return "eligible" if eligible_trace.value else "ineligible"
    if det.unresolved_inputs or det.unresolved_facts:
        return "incomplete"
    return "unknown"


@pytest.mark.skipif(not _CASES, reason=_SKIP_MSG)
@pytest.mark.parametrize("case", _CASES, ids=[c.id for c in _CASES])
def test_synthetic_case(case: TestCase) -> None:
    """Run a synthetic test case through the engine and assert expected outcome."""
    graph = build_fema_ia_graph()
    engine = FactGraphEngine(graph)
    engine.load_facts(case.inputs)
    engine.resolve()

    actual = _actual_determination(engine)
    det = engine.get_determination(scenario_label=case.id)

    assert actual == case.expected_determination, (
        f"Case {case.id!r}: expected={case.expected_determination!r}, got={actual!r}\n"
        f"Rationale: {case.rationale}\n"
        f"Unresolved inputs: {det.unresolved_inputs}\n"
        f"Unresolved facts: {det.unresolved_facts}"
    )

    # Verify expected terminal fact values if specified.
    for fact_id, expected_value in case.expected_terminal_facts.items():
        if fact_id in det.terminal_facts:
            trace = det.terminal_facts[fact_id]
            assert trace.value == expected_value, (
                f"Case {case.id!r}: terminal fact {fact_id!r} expected {expected_value!r}, "
                f"got {trace.value!r}"
            )
        elif fact_id in det.resolved_facts:
            trace = det.resolved_facts[fact_id]
            assert trace.value == expected_value, (
                f"Case {case.id!r}: resolved fact {fact_id!r} expected {expected_value!r}, "
                f"got {trace.value!r}"
            )
        # If the fact is unresolved, skip value assertion (incomplete case).


# ---------------------------------------------------------------------------
# Smoke test: runs even without synthetic_cases.json
# ---------------------------------------------------------------------------

def test_engine_resolves_hand_crafted_eligible_case() -> None:
    """
    Hand-crafted eligible scenario — always runs regardless of synthetic cases file.

    Income: $2,400/month. FMR: $1,600. 30% of income = $720.
    Housing cost: $1,200 > $720 → financial need met.
    Expected max_award = $1,600 - $720 = $880.
    """
    graph = build_fema_ia_graph()
    engine = FactGraphEngine(graph)
    engine.load_facts({
        "primary_residence_damaged_by_disaster": True,
        "primary_residence_is_uninhabitable": True,
        "primary_residence_is_inaccessible": False,
        "made_unavailable_by_landlord": False,
        "has_permanent_housing_plan": True,
        "gross_post_disaster_monthly_income": 2400.0,
        "monthly_housing_cost": 1200.0,
        "fair_market_rent_amount": 1600.0,
        "in_special_flood_hazard_area": False,
        "in_nfip_participating_community": True,
        "insurance_covers_housing_need": False,
        "other_source_provides_assistance": False,
        "flood_insurance_previously_required": False,
        "flood_insurance_previously_maintained": False,
    })
    engine.resolve()
    det = engine.get_determination()

    eligible = det.terminal_facts.get("applicant_eligible_for_rental_assistance")
    assert eligible is not None
    assert eligible.value is True

    award = det.terminal_facts.get("maximum_award_amount")
    assert award is not None
    assert award.value == pytest.approx(880.0)  # 1600 - 720


def test_engine_resolves_hand_crafted_ineligible_case() -> None:
    """
    Hand-crafted ineligible scenario: insurance covers the housing need
    → duplication of benefits → ineligible.
    """
    graph = build_fema_ia_graph()
    engine = FactGraphEngine(graph)
    engine.load_facts({
        "primary_residence_damaged_by_disaster": True,
        "primary_residence_is_uninhabitable": True,
        "primary_residence_is_inaccessible": False,
        "made_unavailable_by_landlord": False,
        "has_permanent_housing_plan": True,
        "gross_post_disaster_monthly_income": 2000.0,
        "monthly_housing_cost": 1500.0,
        "fair_market_rent_amount": 1400.0,
        "in_special_flood_hazard_area": False,
        "in_nfip_participating_community": True,
        "insurance_covers_housing_need": True,  # ← duplicates benefits
        "other_source_provides_assistance": False,
        "flood_insurance_previously_required": False,
        "flood_insurance_previously_maintained": False,
    })
    engine.resolve()
    det = engine.get_determination()

    duplication_trace = det.resolved_facts.get("duplication_of_benefits_clear")
    assert duplication_trace is not None
    assert duplication_trace.value is False

    eligible = det.terminal_facts.get("applicant_eligible_for_rental_assistance")
    assert eligible is not None
    assert eligible.value is False
